=== lrh007/JavaGeneratorFromWord/target/classes/config.dtd
<!--class 根标签 下面有 field 和custom 两个子标签-->
<!ELEMENT class (directory-path,field,custom)>
<!--文件所在目录-->
<!ELEMENT directory-path (#PCDATA)>
<!--子标签 field 标签内容定义成空的-->
<!ELEMENT field EMPTY>
<!--子标签 field 属性设置-->
<!ATTLIST field setter(true|false) "true" (#IMPLIED)>
<!ATTLIST field getter(true|false) "true" (#IMPLIED)>
<!ATTLIST field scope(public|private|protected|default) "public" (#REQUIRED)>
<!ATTLIST field javaType (#REQUIRED)>
<!ATTLIST field staticVar(true|false) "false" (#IMPLIED)>
<!ATTLIST field finalVar(true|false) "false" (#IMPLIED)>
<!ATTLIST field showDescription(true|false) "true" (#IMPLIED)>
<!--子标签custom 下面有 custom-fields 和 custom-methods 两个子标签-->
<!ELEMENT custom (custom-fields,custom-methods)>
<!--子标签 custom-fields 下面有 custom-field 一个子标签-->
<!ELEMENT custom-fields (custom-field)>
<!--子标签 custom-field 下面有 field-name,field-value,field-description 三个子标签-->
<!ELEMENT custom-field (field-name,field-value,field-description)>
<!--子标签 custom-field 属性设置-->
<!ATTLIST custom-field setter(true|false) "true" (#IMPLIED)>
<!ATTLIST custom-field getter(true|false) "true" (#IMPLIED)>
<!ATTLIST custom-field scope(public|private|protected|default) "public" (#REQUIRED)>
<!ATTLIST custom-field javaType (#REQUIRED)>
<!ATTLIST custom-field staticVar(true|false) "false" (#IMPLIED)>
<!ATTLIST custom-field finalVar(true|false) "false" (#IMPLIED)>
<!ATTLIST custom-field allClass(true|false) "true" (#IMPLIED)>
<!--子标签 custom-field 下面的三个子标签都设置成只能填写字符串-->
<!ELEMENT field-name (#PCDATA)>
<!ELEMENT field-value (#PCDATA)>
<!ELEMENT field-description (#PCDATA)>

<!--子标签 custom-methods 下面有 custom-method 一个子标签-->
<!ELEMENT custom-methods (custom-method)>
<!--子标签 custom-method 下面有 method-name,method-annotion,method,method-return,method-params 四个子标签-->
<!ELEMENT custom-method (method-name,method-annotation,method-return,method-params)>
<!--设置子标签下面标签只能填写字符串-->
<!ELEMENT method-name (#PCDATA)>
<!ELEMENT method-annotation (#PCDATA)>
<!ELEMENT method-return (#PCDATA)>
<!--子标签 method-params 下面有 method-param 一个子标签-->
<!ELEMENT method-params (method-param)>
<!--设置method-param 子标签只能填写字符串及属性设置-->
<!ELEMENT method-param (#PCDATA)>
<!ATTLIST method-param javaType (#REQUIRED)>
<!ATTLIST method-param finalVar(true|false) "true" (#IMPLIED)>

<!--子标签custom-method 的属性设置-->
<!ATTLIST custom-method scope(public|private|protected|default) "public" (#REQUIRED)>
<!ATTLIST custom-method javaType (#REQUIRED)>
<!ATTLIST custom-method staticVar(true|false) "false" (#IMPLIED)>
<!ATTLIST custom-method finalVar(true|false) "false" (#IMPLIED)>
<!ATTLIST custom-method allClass(true|false) "true" (#IMPLIED)>

=== lrh007/JavaGeneratorFromWord/target/classes/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE class SYSTEM "config.dtd">-->
<class>
	<directory-path>C:\Users\MACHENIKE\Desktop\cp项目实体类代码生成工具\</directory-path>
	<field setter="true"
		   getter="true"
		   scope="private"
		   javaType="Integer"
		   staticVar="false"
		   finalVar="true"
		   showDescription="true"/>

	<custom>
		<custom-fields>
			<custom-field setter="true"
						  getter="true"
						  scope="public"
						  javaType="String"
						  staticVar="true"
						  finalVar="true"
						  allClass="false"
			>
				<!--allClass 默认true 表示 所有类中都会生成这个自定义属性，false 表示只在有@customer注解的类中才会生成-->
				<field-name>METHOD_URL</field-name>
				<field-value>111</field-value>
				<field-description>请求资方url地址</field-description>
			</custom-field>
			<custom-field setter="true"
						  getter="true"
						  scope="public"
						  javaType="String"
						  staticVar="true"
						  finalVar="true"
						  allClass="false"
			>
				<field-name>LOCAL_PATH</field-name>
				<field-value>111</field-value>
				<field-description>本地请求url地址</field-description>
			</custom-field>
		</custom-fields>
		<custom-methods>
			<custom-method scope="public"
						   javaType="void"
						   staticVar="true"
						   finalVar="true"
						   allClass="true"
			>
				<!--默认true 表示 所有类中都会生成这个自定义属性，false 表示只在有@customer注解的类中才会生成-->
				<method-name>getOrder</method-name>
				<method-annotations><!--方法上面的注解-->
					<method-annotation>@Override</method-annotation>
					<method-annotation>@JSONField(serialize = false)</method-annotation>
				</method-annotations>
				<method-return>LoanApplyResponse.class</method-return> <!--方法的返回值-->
				<method-params>
					<method-param javaType="int" finalVar="true">count</method-param>
					<method-param javaType="String" finalVar="true">name</method-param>
				</method-params>
			</custom-method>
			<custom-method scope="public"
						   javaType="void"
						   staticVar="true"
						   finalVar="true"
						   allClass="true"
			>
				<!--默认true 表示 所有类中都会生成这个自定义属性，false 表示只在有@customer注解的类中才会生成-->
				<method-name>loanOrder</method-name>
				<method-annotations> <!--方法上面的注解-->
					<method-annotation>@Override</method-annotation>
				</method-annotations>
				<method-return>LoanApplyResponse.class</method-return> <!--方法的返回值-->
				<method-params>
					<method-param javaType="int" finalVar="true">count</method-param>
					<method-param javaType="String" finalVar="true">name</method-param>
				</method-params>
			</custom-method>
		</custom-methods>
	</custom>

</class>

=== lrh007/JavaGeneratorFromWord/src/main/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE class SYSTEM "config.dtd">
<class>
	<directory-path>C:/users/</directory-path>
	<field setter="true"
		   getter="true"
		   scope="private"
		   javaType="Integer"
		   staticVar="true"
		   finalVar="true"
		   showDescription="true"/>

	<custom>
		<custom-fields>
			<custom-field setter="true"
					getter="true"
					scope="public"
					javaType="String"
				    staticVar="true"
				    finalVar="true"
					allClass="false"
					>
				<!--allClass 默认true 表示 所有类中都会生成这个自定义属性，false 表示只在有@customer注解的类中才会生成-->
				<field-name>LOCAL_PATH</field-name>
				<field-value>111</field-value>
				<field-description>本地路径</field-description>
			</custom-field>
			<custom-field setter="true"
					getter="true"
					scope="public"
					javaType="String"
				    staticVar="true"
				    finalVar="true"
					>
				<field-name>CLIENT_PATH</field-name>
				<field-value>111</field-value>
				<field-description>远程路径</field-description>
			</custom-field>
		</custom-fields>
		<custom-methods>
			<custom-method scope="public"
					javaType="void"
				    staticVar="true"
				    finalVar="true"
					allClass="true"
					>
<!--				#默认true 表示 所有类中都会生成这个自定义属性，false 表示只在有@customer注解的类中才会生成-->
				<method-name>getOrder</method-name>
				<method-annotations><!--方法上面的注解-->
					<method-annotation>@Override</method-annotation>
					<method-annotation>@JSONField(serialize = false)</method-annotation>
				</method-annotations>
				<method-return>LoanApplyResponse.class</method-return> <!--方法的返回值-->
				<method-params>
					<method-param javaType="int" finalVar="true">count</method-param>
					<method-param javaType="String" finalVar="true">name</method-param>
				</method-params>
			</custom-method>
			<custom-method scope="public"
						   javaType="void"
						   staticVar="true"
						   finalVar="true"
						   allClass="true"
			>
				<!--				#默认true 表示 所有类中都会生成这个自定义属性，false 表示只在有@customer注解的类中才会生成-->
				<method-name>loanOrder</method-name>
				<method-annotations> <!--方法上面的注解-->
					<method-annotation>@Override</method-annotation>
				</method-annotations>
				<method-return>LoanApplyResponse.class</method-return> <!--方法的方绘制-->
				<method-params>
					<method-param javaType="int" finalVar="true">count</method-param>
					<method-param javaType="String" finalVar="true">name</method-param>
				</method-params>
			</custom-method>
		</custom-methods>
	</custom>

</class>
